site/app/(home)/page.tsx
site/app/_components/ThemePreview.tsx
site/app/_utils/content.ts
site/app/features/[slug]/page.tsx
site/app/players/[slug]/page.tsx
site/app/themes/[slug]/page.tsx
site/content-collections.ts
site/features/audio-tracks.md
site/features/timeline-chapters.md
site/features/timeline-thumbnails.md
site/players/dash.md
site/players/hls.md
site/players/mux-video.md
site/players/vimeo.md
site/players/wistia.md
site/players/youtube.md

this adds the basis for future players and features entry pages for searchability.

site: basis of player and features collections

---

package-lock.json
site/app/(home)/page.tsx
site/app/_components/AnalyticsProvider.tsx
site/app/_components/NavBar.tsx
site/app/_components/PostHogPageView.tsx
site/app/layout.tsx
site/package.json

fix #25 
https://player-style-git-posthog-mux.vercel.app/

site: add Posthog

---

package-lock.json
site/app/(home)/page.tsx
site/app/_components/Grid.tsx
site/app/_components/Search.tsx
site/app/_utils/content.ts
site/app/about/page.tsx
site/package.json
site/tsconfig.json

site: implement flexsearch

---

themes/yt/template.html

I added `mediapaused` to the play button to hopefully prevent the transitioning. I wasn't able to reproduce the problem locally in the first place to confirm.
Also prettier kicked in a thousand other changes.

Stop the YT play button from transitioning on load

---

package-lock.json
scripts/build-theme/build.js
scripts/build-theme/package.json
scripts/build-theme/templates/media-theme.js
site/app/_components/PlayerHero.tsx
site/app/_components/ThemePreview.tsx
site/content-collections.ts
site/themes/tailwind-audio.md
themes/tailwind-audio/package.json
themes/tailwind-audio/styles.css
themes/tailwind-audio/tailwind.config.js
themes/tailwind-audio/template.html

feat: add tailwind-audio theme

---

examples/vanilla/index.html
examples/vanilla/script.js
package-lock.json
package.json
site/themes/vimeonova.md
themes/vimeonova/package.json
themes/vimeonova/template.html

bug https://github.com/muxinc/media-chrome/issues/944
medialoading bug and would like to change rendition button icon on resize

feat: add Vimeonova theme

---

themes/vimeonova/template.html

https://player-style-git-vimeonova-color-support-mux.vercel.app/?primary-color=f5ff70&secondary-color=004cff&accent-color=ff8fd0

fix: add Vimeonova color support

---

.github/release-please/.release-please-manifest.json
.github/release-please/release-please-config.json
package-lock.json
package.json
site/themes/instaplay.md
themes/instaplay/package.json
themes/instaplay/template.html

https://player-style-git-instaplay-mux.vercel.app/themes/instaplay
todo:

feat: add Instaplay theme

---

themes/vimeonova/template.html

fix: responsive fullscreen

---

package-lock.json
package.json
site/app/(home)/page.tsx
site/app/_components/DocsEmbed.tsx
site/app/_components/ThemeColorPopover.tsx
site/app/_components/ThemeLink.tsx
site/app/_components/ThemePreview.tsx
site/app/themes/[slug]/page.tsx
site/package.json

1. explain theme colors with new `ThemeColorPopover` component
2. carry theme colors from home to player page with new `ThemeLink` component
3. add theme colors to the code snippet with changes to `DocsEmbed`

Improve theme color experience

---

.github/release-please/.release-please-manifest.json
.github/release-please/release-please-config.json
package-lock.json
package.json
site/app/_components/MediaTheme.tsx
site/app/_components/PlayerHero.tsx
site/app/_components/ThemePreview.tsx
site/content-collections.ts
site/media-assets.ts
site/tailwind.config.js
site/themes/demuxed-2022.md
site/themes/instaplay.md
site/themes/microvideo.md
site/themes/minimal.md
site/themes/sutro-audio.md
site/themes/sutro.md
site/themes/tailwind-audio.md
site/themes/vimeonova.md
site/themes/winamp.md
site/themes/yt.md
themes/sutro-audio/package.json
themes/sutro-audio/template.html
themes/vimeonova/template.html

https://player-style-git-sutro-audio-mux.vercel.app/themes/sutro-audio

feat: add Sutro audio theme

---

package-lock.json
package.json

fix: make themes dev deps, prevent dup deps

---

themes/sutro-audio/template.html
themes/sutro/template.html

fix: mobile overflow. hide duration on mobile

---

themes/instaplay/template.html
themes/notflix/template.html
themes/sutro-audio/template.html
themes/sutro/template.html
themes/vimeonova/template.html
themes/yt/template.html

fix #97
removes a CSS var that doesn't do anything.

fix: empty YT settings menus

---

site/app/_components/DocsEmbed.tsx
site/app/themes/[slug]/page.tsx
site/frameworks/lit.md

https://player-style-git-lit-framework-mux.vercel.app/themes/sutro?framework=lit

site: add Lit framework embed option

---

site/app/(home)/page.tsx
site/app/_components/NavBar.tsx
site/app/_components/ThemePreview.tsx

https://player-style-git-banner-mux.vercel.app/

site: hero copy refresh + add steps banner

---

site/app/(home)/page.tsx
site/app/_components/DocsEmbed.tsx
site/app/_components/Hero.tsx
site/app/themes/[slug]/page.tsx

Update header copy. 
Also move color setting to the bottom of the filter menu. It feels important to have the search at the top.

Rewrite homepage content

---

site/features/airplay.md
site/features/google-cast.md
site/themes/demuxed-2022.md
site/themes/microvideo.md
site/themes/minimal.md
site/themes/sutro.md
site/themes/vimeonova.md

for easy filtering on these features!
https://player-style-git-cast-airplay-features-mux.vercel.app/

site: add google cast and airplay feature filter

---

package-lock.json
package.json
site/package.json
themes/demuxed-2022/template.html
themes/halloween/template.html
themes/instaplay/template.html
themes/microvideo/template.html
themes/minimal/template.html
themes/notflix/template.html
themes/reelplay/template.html
themes/sutro/template.html
themes/vimeonova/template.html
themes/x-mas/template.html
themes/yt/template.html

- adds the new Media Chrome error dialog https://github.com/muxinc/media-chrome/pull/1024
- adds the fixed playback core error bug https://github.com/muxinc/elements/pull/1014

feat: add error dialog

---

site/app/_components/DocsEmbed.tsx

set crossorigin to anonymous in embed code
